import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { loadModules } from "@/lib/load-modules";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const modulesData = await loadModules(); // ✅ Load modules on the server

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
